FROM cimg/node:18.17.0

# 
# !!!!!!!!!!!!!!!!!!!!! CAUTION !!!!!!!!!!!!!!!!!!!!!
#  This is public image !!!!!!!!!
#  このイメージは外部に公開されるイメージのためパスワードなどのクレデンシャルを埋め込まないでください
# 

ENV DEBIAN_FRONTEND=noninteractive

# Install JRE for firebase emulator
RUN sudo apt-get update  && \
    sudo apt-get install -y default-jre && \
    sudo rm -rf /var/lib/apt/lists

LABEL com.circleci.preserve-entrypoint=true
